inpta/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('inptadb/', include('inptadb.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
]

inptadb/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('projects', views.projects, name='projects'),
    path('project/<int:project_id>', views.project, name='project'),
    path('proposal/<int:proposal_id>', views.proposal, name='proposal')
]

inptadb/models.py
from django.db import models

# Create your models here.

class Project(models.Model):
    name = models.CharField(max_length=10)
    longname = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Telescope(models.Model):
    name = models.CharField(max_length=10)
    longname = models.CharField(max_length=100)

    def __str__(self):
        return self.name
  
class Backend(models.Model):
    telescope = models.ForeignKey(Telescope, on_delete=models.CASCADE)
    name = models.CharField(max_length=10)
    longname = models.CharField(max_length=100)

    def __str__(self):
        return "{}/{}".format(self.telescope.name, self.name)

class Astronomer(models.Model):
    name = models.CharField(max_length=150)

    def __str__(self):
        return self.name

class Proposal(models.Model):
    telescope = models.ForeignKey(Telescope, on_delete=models.CASCADE)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    code = models.CharField(max_length=10)
    title = models.CharField(max_length=250)
    principal_investigator = models.ForeignKey(Astronomer, on_delete=models.CASCADE)
    year = models.IntegerField()
    cycle = models.IntegerField()
    date_submitted = models.DateField()
    date_decided = models.DateField()
    accepted = models.BooleanField()
    filename = models.CharField(max_length=250)

    def __str__(self):
        return "{}/{}".format(self.telescope.name, self.code)

class Session(models.Model):
    proposal = models.ForeignKey(Proposal, on_delete=models.CASCADE)
    observer = models.ForeignKey(Astronomer, on_delete=models.CASCADE)
    start_time = models.DateTimeField()
    stop_time = models.DateTimeField()
    backend = models.ForeignKey(Backend, on_delete=models.CASCADE)
    setupfile = models.CharField(max_length=250)
    commandfile = models.CharField(max_length=250)

    def __str__(self):
        return "{}_starting_from_{}".format(self.proposal, self.start_time)

class SourceType(models.Model):
    name = models.CharField(max_length=10)

    def __str__(self):
        return self.name

class Source(models.Model):
    name = models.CharField(max_length=10)
    srctype = models.ForeignKey(SourceType, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class DataFormat(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

class Observation(models.Model):
    session = models.ForeignKey(Session, on_delete=models.CASCADE)
    source = models.ForeignKey(Source, on_delete=models.CASCADE)
    lofreq = models.FloatField()
    bandwidth = models.FloatField()
    nbit = models.IntegerField()
    nchan = models.IntegerField()
    tsmpl = models.FloatField()
    usb = models.BooleanField()
    npol = models.IntegerField()
    interferometer_mode = models.CharField(max_length=2)
    coherent_dedispersion = models.BooleanField()
    data_format = models.ForeignKey(DataFormat, on_delete=models.CASCADE)
    data_filename = models.CharField(max_length=250)
    interferometry_filename = models.CharField(max_length=250, null=True, blank=True)
    timestamp_filename = models.CharField(max_length=250)
    start_time = models.DateTimeField()
    duration = models.FloatField()

    def __str__(self):
        return "{}_observation_of_{}_starting_from_{}".format(self.proposal, self.pulsar, self.start_time)

class Archive(models.Model):
    observation = models.ForeignKey(Observation, on_delete=models.CASCADE)
    data_format = models.ForeignKey(DataFormat, on_delete=models.CASCADE)
    filename = models.CharField(max_length=250)
    analyzer = models.ForeignKey(Astronomer, on_delete=models.CASCADE)

inptadb/views.py
from django.shortcuts import render
from django.http import HttpResponse

from .models import Project, Proposal

def index(request):
    context = dict()
    return render(request, 'inptadb/index.html', context)
    #return HttpResponse("Welcome to InPTA!")

def projects(request):
    projects = Project.objects.all()
    context = {"projects" : projects}
    return render(request, 'inptadb/projects.html', context)
    
def project(request, project_id):
    try:
        project = Project.objects.get(pk=project_id)
    except Project.DoesNotExist:
        raise Http404("Project Does Not Exist.")
    #response = "Showing Question #{}".format(question_id)
    return render(request, "inptadb/project.html", {'project':project})

def proposal(request, proposal_id):
    try:
        proposal = Proposal.objects.get(pk=proposal_id)
    except Project.DoesNotExist:
        raise Http404("Proposal Does Not Exist.")
    #response = "Showing Question #{}".format(question_id)
    return render(request, "inptadb/proposal.html", {'proposal':proposal})

inptadb/templates/base.html
<!DOCTYPE html>
<html>
{% load static %}
  <head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <link rel="stylesheet" href="{% static 'inptadb/inpta.css' %}">
    <title>InPTA data archive</title>
  </head>
  <body>
    <div id="banner">
      <div id="banner-content"> 
        <table border="0" width='90%'>
        <tbody>
            <tr>
              <td><a href="{% url 'index' %}">
                  <img src="{% static 'inptadb/InPTA-logo.png' %}" alt="InPTA Logo" style="height:50px;width:auto"> 
              </a></td>
              <td style="text-align:right; vertical-align:bottom;">
	            {% if user.is_authenticated %}
	              Logged in as {{ user.username }}. 
	              <a href="{% url 'logout' %}">Log out</a>
	            {% else %}
	              <a href="{% url 'login' %}">Log in</a>
	            {%endif%}  
              </td>
            </tr>
        </tbody>
        </table>
      </div>
    </div>
    <br/>
    <div id="main-content">
    {% block loginform %} {% endblock %}
    
    {% if user.is_authenticated %}
      {% block content %}  {% endblock %}
    {% endif %}
    </div>
  </body>
</html>

inptadb/templates/inptadb/index.html
{% extends "base.html" %}

{% block content %}
  <br>
  <h1>Welcome to InPTA project archive.</h1>
  <p>Click <a href="{% url 'project' 1 %}">here</a> to view InPTA observations.</p>
  <p>Click <a href="{% url 'projects' %}">here</a> to view all projects in this archive.</p>
{% endblock %}

inptadb/templates/inptadb/project.html
{% extends "base.html" %}

{% block content %}
      <h2>Project : {{ project.longname }} ({{project.name}})</h2>
      <br/>
      <table style="width: 100%" border="1">
      <tbody>
        <tr>
          <td><strong>Telescope/Proposal</strong></td>
          <td><strong>Cycle</strong></td>
          <td><strong>Title</strong></td>
          <td><strong>Date of submission</strong></td>
          <td><strong>Accepted</strong></td>
          <td><strong>No. of observing sessions</strong></td>
        </tr>
        {% for proposal in project.proposal_set.all %}
        <tr>
          <td>{{ proposal.telescope.name }}/{{ proposal.code }}</td>
          <td>{{ proposal.cycle }}</td>
          <td>{{ proposal.title }}</td>
          <td>{{ proposal.date_submitted }}</td>
          <td>{{ proposal.accepted|yesno:"Yes,No" }}</td>
          <td>{{ proposal.session_set.count }} (View) </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
{% endblock %}

inptadb/templates/inptadb/projects.html
{% extends "base.html" %}

{% block content %}
  <h1>Projects</h1>
  <br/>
  <ul style="list-style-type:circle">
    {% for project in projects %}
    <li><a href="{% url 'project' project.id %}">{{ project.longname }} ({{ project.name }})</a></li>
    {% endfor %}
  </ul>
{% endblock %}

inptadb/templates/inptadb/proposal.html
{% extends "base.html" %}

{% block content %}
  <h1>Observing Sessions for {{ proposal }}</h1>
  <br/>
  <ul style="list-style-type:circle">
    {% for session in proposal.session_set.all %}
    <li>{{ session }}</li>
    {% endfor %}
  </ul>
{% endblock %}

inptadb/templates/inptadb/sessions.html
{% extends "base.html" %}

{% block content %}
  <h1>Observing Sessions for {{ proposal }}</h1>
  <br/>
  <ul style="list-style-type:circle">
    {% for session in proposal.session_set.all %}
    <li>{{ session }}</li>
    {% endfor %}
  </ul>
{% endblock %}